# Autoassociative Hopfield network

# (a)

In [60]:
import numpy as np

# input training patterns

A_letter = """
.#.
#.#
###
#.#
#.#
"""
A_label = [-1, -1, -1]

D_letter = """
##.
#.#
#.#
#.#
##.
"""
D_label = [-1, 1, 1]

H_letter = """
#.#
#.#
###
#.#
#.#
"""
H_label = [1, 1, 1]

# convert to training matrix and label matrix
def pattern_to_matrix(letter):
    return np.array([+1 if item=='#' else -1 for item in letter.replace('\n','')])

train_set = np.array([pattern_to_matrix(A_letter), pattern_to_matrix(D_letter), pattern_to_matrix(H_letter)])
y_set = np.array([A_label, D_label, H_label])
print(train_set.shape)
print(train_set)
print(y_set.shape)
print(y_set)

(3, 15)
[[-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
 [ 1  1 -1  1 -1  1  1 -1  1  1 -1  1  1  1 -1]
 [ 1 -1  1  1 -1  1  1  1  1  1 -1  1  1 -1  1]]
(3, 3)
[[-1 -1 -1]
 [-1  1  1]
 [ 1  1  1]]


In [61]:
# Create an autoassociative Hopfield network and train on these three patterns
# Initialize the weight matrix 
W = np.dot(train_set.T, train_set)
print(W.shape)
print(W)
# set W_ij = 0
np.fill_diagonal(W, 0)
W

(15, 15)
[[ 3 -1  1  1 -1  1  1 -1  1  1 -1  1  1  1 -1]
 [-1  3 -3  1 -1  1  1 -1  1  1 -1  1  1  1 -1]
 [ 1 -3  3 -1  1 -1 -1  1 -1 -1  1 -1 -1 -1  1]
 [ 1  1 -1  3 -3  3  3  1  3  3 -3  3  3 -1  1]
 [-1 -1  1 -3  3 -3 -3 -1 -3 -3  3 -3 -3  1 -1]
 [ 1  1 -1  3 -3  3  3  1  3  3 -3  3  3 -1  1]
 [ 1  1 -1  3 -3  3  3  1  3  3 -3  3  3 -1  1]
 [-1 -1  1  1 -1  1  1  3  1  1 -1  1  1 -3  3]
 [ 1  1 -1  3 -3  3  3  1  3  3 -3  3  3 -1  1]
 [ 1  1 -1  3 -3  3  3  1  3  3 -3  3  3 -1  1]
 [-1 -1  1 -3  3 -3 -3 -1 -3 -3  3 -3 -3  1 -1]
 [ 1  1 -1  3 -3  3  3  1  3  3 -3  3  3 -1  1]
 [ 1  1 -1  3 -3  3  3  1  3  3 -3  3  3 -1  1]
 [ 1  1 -1 -1  1 -1 -1 -3 -1 -1  1 -1 -1  3 -3]
 [-1 -1  1  1 -1  1  1  3  1  1 -1  1  1 -3  3]]


array([[ 0, -1,  1,  1, -1,  1,  1, -1,  1,  1, -1,  1,  1,  1, -1],
       [-1,  0, -3,  1, -1,  1,  1, -1,  1,  1, -1,  1,  1,  1, -1],
       [ 1, -3,  0, -1,  1, -1, -1,  1, -1, -1,  1, -1, -1, -1,  1],
       [ 1,  1, -1,  0, -3,  3,  3,  1,  3,  3, -3,  3,  3, -1,  1],
       [-1, -1,  1, -3,  0, -3, -3, -1, -3, -3,  3, -3, -3,  1, -1],
       [ 1,  1, -1,  3, -3,  0,  3,  1,  3,  3, -3,  3,  3, -1,  1],
       [ 1,  1, -1,  3, -3,  3,  0,  1,  3,  3, -3,  3,  3, -1,  1],
       [-1, -1,  1,  1, -1,  1,  1,  0,  1,  1, -1,  1,  1, -3,  3],
       [ 1,  1, -1,  3, -3,  3,  3,  1,  0,  3, -3,  3,  3, -1,  1],
       [ 1,  1, -1,  3, -3,  3,  3,  1,  3,  0, -3,  3,  3, -1,  1],
       [-1, -1,  1, -3,  3, -3, -3, -1, -3, -3,  0, -3, -3,  1, -1],
       [ 1,  1, -1,  3, -3,  3,  3,  1,  3,  3, -3,  0,  3, -1,  1],
       [ 1,  1, -1,  3, -3,  3,  3,  1,  3,  3, -3,  3,  0, -1,  1],
       [ 1,  1, -1, -1,  1, -1, -1, -3, -1, -1,  1, -1, -1,  0, -3],
       [-1, -1,  1,  1, -1,  1,  1

# (b)

In [62]:
# Test the recall on the same three patterns

# do recall
def to_recall(pattern):
    y_i = pattern
    for i in range(0, len(pattern)):
        # Compute net input
        #y_i = pattern
        w_ji = W[:,i]
        y_in_i = pattern[i] + np.dot(y_i, w_ji)
        # Determine activation (threthod = 0, and using bipolar activation function)
        if y_in_i > 0:
            y_out = 1
        if y_in_i < 0:
            y_out = -1
        else:
            y_out = y_i[i]
        y_i[i] = y_out
        print("For n", str(i+1), "Net= ", y_in_i, ", Out= ", y_out, ", upated y_i: ", y_i)
    return y_i

acc_count = 0
for pattern_index in range(0,train_set.shape[0]):
    # Do test for each unit
    print("Test on pattern ", str(pattern_index+1), train_set[pattern_index])
    print("First round")
    y_i_1st = to_recall(train_set[pattern_index])
    print("Second round")
    y_i_2nd = to_recall(y_i_1st)
    # check convergence
    if np.array_equal(y_i_1st, y_i_2nd):
        print(y_i_2nd, " achieves convergence.")
    else:
        print(y_i_2nd, " may need one more iteration.")
    # check if it is successfully recalled
    if np.array_equal(y_i_2nd, train_set[pattern_index]):
        print("Successfully recalled.")
        acc_count += 1
    else:
        print("Not successfully recalled.")
print("Classification accuracy: ", '%.2f' % (acc_count/3))

Test on pattern  1 [-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
First round
For n 1 Net=  3 , Out=  -1 , upated y_i:  [-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
For n 2 Net=  11 , Out=  1 , upated y_i:  [-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
For n 3 Net=  -11 , Out=  -1 , upated y_i:  [-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
For n 4 Net=  29 , Out=  1 , upated y_i:  [-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
For n 5 Net=  -29 , Out=  -1 , upated y_i:  [-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
For n 6 Net=  29 , Out=  1 , upated y_i:  [-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
For n 7 Net=  29 , Out=  1 , upated y_i:  [-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
For n 8 Net=  15 , Out=  1 , upated y_i:  [-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
For n 9 Net=  29 , Out=  1 , upated y_i:  [-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
For n 10 Net=  29 , Out=  1 , upated y_i:  [-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
For n 11 Net=  -29 , Out=  

# Problem 4 (c)

In [54]:
# slightly change training patterns: changing 1 item

A_letter_sl = """
.#.
#.#
###
###
#.#
"""

D_letter_sl = """
##.
#.#
###
#.#
##.
"""

H_letter_sl = """
#.#
#.#
###
###
#.#
"""

# convert to training matrix and label matrix
def pattern_to_matrix(letter):
    return np.array([+1 if item=='#' else -1 for item in letter.replace('\n','')])

train_set_sl = np.array([pattern_to_matrix(A_letter_sl), pattern_to_matrix(D_letter_sl), pattern_to_matrix(H_letter_sl)])
print(train_set_sl.shape)
print(train_set_sl)

(3, 15)
[[-1  1 -1  1 -1  1  1  1  1  1  1  1  1 -1  1]
 [ 1  1 -1  1 -1  1  1  1  1  1 -1  1  1  1 -1]
 [ 1 -1  1  1 -1  1  1  1  1  1  1  1  1 -1  1]]


In [55]:
# do recall
def to_recall(pattern):
    y_i = pattern
    for i in range(0, len(pattern)):
        # Compute net input
        #y_i = pattern
        w_ji = W[:,i]
        y_in_i = pattern[i] + np.dot(y_i, w_ji)
        # Determine activation (threthod = 0, and using bipolar activation function)
        if y_in_i > 0:
            y_out = 1
        if y_in_i < 0:
            y_out = -1
        else:
            y_out = y_i[i]
        y_i[i] = y_out
        print("For n", str(i+1), "Net= ", y_in_i, ", Out= ", y_out, ", upated y_i: ", y_i)
    return y_i

acc_count = 0
for pattern_index in range(0,train_set_sl.shape[0]):
    # Do test for each unit
    print("Test on pattern ", str(pattern_index+1), train_set_sl[pattern_index])
    print("First round")
    y_i_1st = to_recall(train_set_sl[pattern_index])
    print("Second round")
    y_i_2nd = to_recall(y_i_1st)
    # check convergence
    if np.array_equal(y_i_1st, y_i_2nd):
        print(y_i_2nd, " achieves convergence.")
    else:
        print(y_i_2nd, " may need one more iteration.")
    # check if it is successfully recalled
    if np.array_equal(y_i_2nd, train_set[pattern_index]):
        print("Successfully recalled.")
        acc_count += 1
    else:
        print("Not successfully recalled.")
print("Classification accuracy: ", '%.2f' % (acc_count/3))

Test on pattern  1 [-1  1 -1  1 -1  1  1  1  1  1  1  1  1 -1  1]
First round
For n 1 Net=  1 , Out=  -1 , upated y_i:  [-1  1 -1  1 -1  1  1  1  1  1  1  1  1 -1  1]
For n 2 Net=  9 , Out=  1 , upated y_i:  [-1  1 -1  1 -1  1  1  1  1  1  1  1  1 -1  1]
For n 3 Net=  -9 , Out=  -1 , upated y_i:  [-1  1 -1  1 -1  1  1  1  1  1  1  1  1 -1  1]
For n 4 Net=  23 , Out=  1 , upated y_i:  [-1  1 -1  1 -1  1  1  1  1  1  1  1  1 -1  1]
For n 5 Net=  -23 , Out=  -1 , upated y_i:  [-1  1 -1  1 -1  1  1  1  1  1  1  1  1 -1  1]
For n 6 Net=  23 , Out=  1 , upated y_i:  [-1  1 -1  1 -1  1  1  1  1  1  1  1  1 -1  1]
For n 7 Net=  23 , Out=  1 , upated y_i:  [-1  1 -1  1 -1  1  1  1  1  1  1  1  1 -1  1]
For n 8 Net=  13 , Out=  1 , upated y_i:  [-1  1 -1  1 -1  1  1  1  1  1  1  1  1 -1  1]
For n 9 Net=  23 , Out=  1 , upated y_i:  [-1  1 -1  1 -1  1  1  1  1  1  1  1  1 -1  1]
For n 10 Net=  23 , Out=  1 , upated y_i:  [-1  1 -1  1 -1  1  1  1  1  1  1  1  1 -1  1]
For n 11 Net=  -27 , Out=  -1

In [39]:
# severely change training patterns: changing 5 item

A_letter_sv = """
##.
#..
#.#
..#
#..
"""

D_letter_sv = """
.#.
###
..#
#..
#..
"""

H_letter_sv = """
..#
..#
.##
###
..#
"""

# convert to training matrix and label matrix
def pattern_to_matrix(letter):
    return np.array([+1 if item=='#' else -1 for item in letter.replace('\n','')])

train_set_sv = np.array([pattern_to_matrix(A_letter_sv), pattern_to_matrix(D_letter_sv), pattern_to_matrix(H_letter_sv)])
print(train_set_sv.shape)
print(train_set_sv)

(3, 15)
[[ 1  1 -1  1 -1 -1  1 -1  1 -1 -1  1  1 -1 -1]
 [-1  1 -1  1  1  1 -1 -1  1  1 -1 -1  1 -1 -1]
 [-1 -1  1 -1 -1  1 -1  1  1  1  1  1 -1 -1  1]]


In [47]:
# do recall
def to_recall(pattern):
    y_i = pattern
    for i in range(0, len(pattern)):
        # Compute net input
        #y_i = pattern
        w_ji = W[:,i]
        y_in_i = pattern[i] + np.dot(y_i, w_ji)
        # Determine activation (threthod = 0, and using bipolar activation function)
        if y_in_i > 0:
            y_out = 1
        if y_in_i < 0:
            y_out = -1
        else:
            y_out = y_i[i]
        y_i[i] = y_out
        print("For n", str(i+1), "Net= ", y_in_i, ", Out= ", y_out, ", upated y_i: ", y_i)
    return y_i

acc_count = 0
for pattern_index in range(0,train_set_sv.shape[0]):
    # Do test for each unit
    print("Test on pattern ", str(pattern_index+1), train_set_sv[pattern_index])
    print("First round")
    y_i_1st = to_recall(train_set_sv[pattern_index])
    print("Second round")
    y_i_2nd = to_recall(y_i_1st)
    # check convergence
    if np.array_equal(y_i_1st, y_i_2nd):
        print(y_i_2nd, " achieves convergence.")
    else:
        print(y_i_2nd, " may need one more iteration.")
    # check if it is successfully recalled
    if np.array_equal(y_i_2nd, train_set[pattern_index]):
        print("Successfully recalled.")
        acc_count += 1
    else:
        print("Not successfully recalled.")
print("Classification accuracy: ", '%.2f' % (acc_count/3))

Test on pattern  1 [ 1  1 -1  1 -1 -1  1 -1  1 -1 -1  1  1 -1 -1]
First round
For n 1 Net=  5 , Out=  1 , upated y_i:  [ 1  1 -1  1 -1 -1  1 -1  1 -1 -1  1  1 -1 -1]
For n 2 Net=  9 , Out=  1 , upated y_i:  [ 1  1 -1  1 -1 -1  1 -1  1 -1 -1  1  1 -1 -1]
For n 3 Net=  -9 , Out=  -1 , upated y_i:  [ 1  1 -1  1 -1 -1  1 -1  1 -1 -1  1  1 -1 -1]
For n 4 Net=  15 , Out=  1 , upated y_i:  [ 1  1 -1  1 -1 -1  1 -1  1 -1 -1  1  1 -1 -1]
For n 5 Net=  -15 , Out=  -1 , upated y_i:  [ 1  1 -1  1 -1 -1  1 -1  1 -1 -1  1  1 -1 -1]
For n 6 Net=  19 , Out=  -1 , upated y_i:  [ 1  1 -1  1 -1 -1  1 -1  1 -1 -1  1  1 -1 -1]
For n 7 Net=  15 , Out=  1 , upated y_i:  [ 1  1 -1  1 -1 -1  1 -1  1 -1 -1  1  1 -1 -1]
For n 8 Net=  1 , Out=  -1 , upated y_i:  [ 1  1 -1  1 -1 -1  1 -1  1 -1 -1  1  1 -1 -1]
For n 9 Net=  15 , Out=  1 , upated y_i:  [ 1  1 -1  1 -1 -1  1 -1  1 -1 -1  1  1 -1 -1]
For n 10 Net=  19 , Out=  -1 , upated y_i:  [ 1  1 -1  1 -1 -1  1 -1  1 -1 -1  1  1 -1 -1]
For n 11 Net=  -15 , Out=  -

# BAM Network

# (a)

In [48]:
# Create a heteroassociative BAM network and train on these three patterns (15 inputs, and 3 outputs).
# Calculate the weight matrix

A = np.dot(train_set.T, y_set)
print(A.shape)
print(A)

(15, 3)
[[ 1  3  3]
 [-3 -1 -1]
 [ 1 -1 -1]
 [-1  1  1]
 [ 1 -1 -1]
 [-1  1  1]
 [-1  1  1]
 [ 1 -1 -1]
 [-1  1  1]
 [-1  1  1]
 [ 1 -1 -1]
 [-1  1  1]
 [-1  1  1]
 [-1  1  1]
 [ 1 -1 -1]]


# (b)

In [69]:
# Test the recall on the three patterns.

def output(layer, weight_matrix):
    net = np.dot(layer, weight_matrix)
    print("Net: ", net, "Output: ", np.sign(net))
    return np.sign(net)

acc_count = 0
for pattern_index in range(0, train_set.shape[0]):
    print("Test on pattern ", str(pattern_index+1), train_set[pattern_index])
    print("X_layer to Y_layer - 1st round")
    output_y_1st = output(train_set[pattern_index], A)
    print("Y_layer to X_layer - 1st round")
    output_x_1st = output(output_y_1st, A.T)
    print("X_layer to Y_layer - 2nd round")
    output_y_2nd = output(output_x_1st, A)
    print("Y_layer to X_layer - 2nd round")
    output_x_2nd = output(output_y_2nd, A.T)
    # check convergence
    if np.array_equal(output_y_1st, output_y_2nd) and np.array_equal(output_x_1st, output_x_2nd):
        print("X and Y have reached convergence.")
    else:
        print("X and Y may need one more iteration.")
    # check if it is successfully recalled
    #if np.array_equal(output_y_2nd, y_set[pattern_index]):
    if np.array_equal(output_x_2nd, train_set[pattern_index]):
        print("Successfully recalled.")
        acc_count += 1
    else:
        print("Not successfully recalled.")
print("Classification accuracy: ", '%.2f' % (acc_count/3))

Test on pattern  1 [-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
X_layer to Y_layer - 1st round
Net:  [-11   3   3] Output:  [-1  1  1]
Y_layer to X_layer - 1st round
Net:  [ 5  1 -3  3 -3  3  3 -3  3  3 -3  3  3  3 -3] Output:  [ 1  1 -1  1 -1  1  1 -1  1  1 -1  1  1  1 -1]
X_layer to Y_layer - 2nd round
Net:  [-15  15  15] Output:  [-1  1  1]
Y_layer to X_layer - 2nd round
Net:  [ 5  1 -3  3 -3  3  3 -3  3  3 -3  3  3  3 -3] Output:  [ 1  1 -1  1 -1  1  1 -1  1  1 -1  1  1  1 -1]
X and Y have reached convergence.
Not successfully recalled.
Test on pattern  2 [ 1  1 -1  1 -1  1  1 -1  1  1 -1  1  1  1 -1]
X_layer to Y_layer - 1st round
Net:  [-15  15  15] Output:  [-1  1  1]
Y_layer to X_layer - 1st round
Net:  [ 5  1 -3  3 -3  3  3 -3  3  3 -3  3  3  3 -3] Output:  [ 1  1 -1  1 -1  1  1 -1  1  1 -1  1  1  1 -1]
X_layer to Y_layer - 2nd round
Net:  [-15  15  15] Output:  [-1  1  1]
Y_layer to X_layer - 2nd round
Net:  [ 5  1 -3  3 -3  3  3 -3  3  3 -3  3  3  3 -3] Output:  [ 1  1 -1 

# Problem 5 (c)

In [71]:
# Test recall on the slightly changed set

acc_count = 0
for pattern_index in range(0, train_set_sl.shape[0]):
    print("Test on pattern ", str(pattern_index+1), train_set_sl[pattern_index])
    print("X_layer to Y_layer - 1st round")
    output_y_1st = output(train_set_sl[pattern_index], A)
    print("Y_layer to X_layer - 1st round")
    output_x_1st = output(output_y_1st, A.T)
    print("X_layer to Y_layer - 2nd round")
    output_y_2nd = output(output_x_1st, A)
    print("Y_layer to X_layer - 2nd round")
    output_x_2nd = output(output_y_2nd, A.T)
    # check convergence
    if np.array_equal(output_y_1st, output_y_2nd) and np.array_equal(output_x_1st, output_x_2nd):
        print("X and Y have reached convergence.")
    else:
        print("X and Y may need one more iteration.")
    # check if it is successfully recalled
    if np.array_equal(output_y_2nd, y_set[pattern_index]):
    #if np.array_equal(output_x_2nd, train_set_sl[pattern_index]):
        print("Successfully recalled.")
        acc_count += 1
    else:
        print("Not successfully recalled.")
print("Classification accuracy: ", '%.2f' % (acc_count/3))

Test on pattern  1 [-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
X_layer to Y_layer - 1st round
Net:  [-11   3   3] Output:  [-1  1  1]
Y_layer to X_layer - 1st round
Net:  [ 5  1 -3  3 -3  3  3 -3  3  3 -3  3  3  3 -3] Output:  [ 1  1 -1  1 -1  1  1 -1  1  1 -1  1  1  1 -1]
X_layer to Y_layer - 2nd round
Net:  [-15  15  15] Output:  [-1  1  1]
Y_layer to X_layer - 2nd round
Net:  [ 5  1 -3  3 -3  3  3 -3  3  3 -3  3  3  3 -3] Output:  [ 1  1 -1  1 -1  1  1 -1  1  1 -1  1  1  1 -1]
X and Y have reached convergence.
Not successfully recalled.
Test on pattern  2 [ 1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1 -1]
X_layer to Y_layer - 1st round
Net:  [-11  11  11] Output:  [-1  1  1]
Y_layer to X_layer - 1st round
Net:  [ 5  1 -3  3 -3  3  3 -3  3  3 -3  3  3  3 -3] Output:  [ 1  1 -1  1 -1  1  1 -1  1  1 -1  1  1  1 -1]
X_layer to Y_layer - 2nd round
Net:  [-15  15  15] Output:  [-1  1  1]
Y_layer to X_layer - 2nd round
Net:  [ 5  1 -3  3 -3  3  3 -3  3  3 -3  3  3  3 -3] Output:  [ 1  1 -1 

In [72]:
# Test recall on the severely changed set

acc_count = 0
for pattern_index in range(0, train_set_sv.shape[0]):
    print("Test on pattern ", str(pattern_index+1), train_set_sv[pattern_index])
    print("X_layer to Y_layer - 1st round")
    output_y_1st = output(train_set_sv[pattern_index], A)
    print("Y_layer to X_layer - 1st round")
    output_x_1st = output(output_y_1st, A.T)
    print("X_layer to Y_layer - 2nd round")
    output_y_2nd = output(output_x_1st, A)
    print("Y_layer to X_layer - 2nd round")
    output_x_2nd = output(output_y_2nd, A.T)
    # check convergence
    if np.array_equal(output_y_1st, output_y_2nd) and np.array_equal(output_x_1st, output_x_2nd):
        print("X and Y have reached convergence.")
    else:
        print("X and Y may need one more iteration.")
    # check if it is successfully recalled
    #if np.array_equal(output_y_2nd, y_set[pattern_index]):
    if np.array_equal(output_x_2nd, train_set_sv[pattern_index]):
        print("Successfully recalled.")
        acc_count += 1
    else:
        print("Not successfully recalled.")
print("Classification accuracy: ", '%.2f' % (acc_count/3))

Test on pattern  1 [ 1  1 -1  1 -1 -1  1 -1  1 -1 -1  1  1 -1 -1]
X_layer to Y_layer - 1st round
Net:  [-9  9  9] Output:  [-1  1  1]
Y_layer to X_layer - 1st round
Net:  [ 5  1 -3  3 -3  3  3 -3  3  3 -3  3  3  3 -3] Output:  [ 1  1 -1  1 -1  1  1 -1  1  1 -1  1  1  1 -1]
X_layer to Y_layer - 2nd round
Net:  [-15  15  15] Output:  [-1  1  1]
Y_layer to X_layer - 2nd round
Net:  [ 5  1 -3  3 -3  3  3 -3  3  3 -3  3  3  3 -3] Output:  [ 1  1 -1  1 -1  1  1 -1  1  1 -1  1  1  1 -1]
X and Y have reached convergence.
Not successfully recalled.
Test on pattern  2 [-1  1 -1  1 -1  1 -1 -1  1  1 -1 -1  1 -1 -1]
X_layer to Y_layer - 1st round
Net:  [-11   3   3] Output:  [-1  1  1]
Y_layer to X_layer - 1st round
Net:  [ 5  1 -3  3 -3  3  3 -3  3  3 -3  3  3  3 -3] Output:  [ 1  1 -1  1 -1  1  1 -1  1  1 -1  1  1  1 -1]
X_layer to Y_layer - 2nd round
Net:  [-15  15  15] Output:  [-1  1  1]
Y_layer to X_layer - 2nd round
Net:  [ 5  1 -3  3 -3  3  3 -3  3  3 -3  3  3  3 -3] Output:  [ 1  1 -1  1 